# Generated by Django 3.2.3 on 2021-06-01 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title_image',
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_image', models.ImageField(blank=True, upload_to='posts/%Y/%m/%d')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='community.post')),
            ],
        ),
    ]
